kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: read-pods-global
subjects:
- kind: User
  # TODO: change the role name to the one you need
  name: system:serviceaccount:REPLACEME:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: kube-stuck-pod-reaper-role
  apiGroup: rbac.authorization.k8s.io
